import type { Locale } from "../../lib/site";

export type TravelLinkCopy = {
  title: string;
  description: string;
  heading: string;
  intro: string;
  workspaceTitle: string;
  workspaceDescription: string;
  marketLabel: string;
  marketPlaceholder: string;
  hotelUrlLabel: string;
  clear: string;
  urlPlaceholder: string;
  urlNote: string;
  generate: string;
  resultsTitle: string;
  resultsDescription: string;
  routeLabel: string;
  allRoutes: string;
  hotelRoutes: string;
  officialRoutes: string;
  searchRoutes: string;
  hotelGroup: string;
  searchGroup: string;
  officialGroup: string;
  empty: string;
  selectMarket: string;
  invalidUrl: string;
  catalogUnavailable: string;
  preservesHotel: string;
  doesNotPreserveHotel: string;
  eligibility: string;
  openOfficial: string;
  openAgoda: string;
  paymentTitle: string;
  paymentDescription: string;
  markets: Record<string, string>;
};

export const travelLinkCopy: Record<Locale, TravelLinkCopy> = {
  en: {
    title: "Find the lowest Agoda hotel price | AbsolTools",
    description:
      "Compare card and partner routes from one Agoda hotel link to find the lowest price.",
    heading: "Find the lowest Agoda hotel price",
    intro:
      "Choose your card market, then compare the displayed prices across Agoda routes.",
    workspaceTitle: "Lowest-price comparison",
    workspaceDescription: "One hotel link, multiple card and partner routes.",
    marketLabel: "Card issuing country or region",
    marketPlaceholder: "Choose country or region",
    hotelUrlLabel: "Agoda hotel URL",
    clear: "Clear",
    urlPlaceholder: "agoda.com/... or https://www.agoda.com/...",
    urlNote: "Existing CID and tracking parameters are not kept.",
    generate: "Compare lowest prices",
    resultsTitle: "Compare Agoda prices",
    resultsDescription:
      "Open each route in Agoda to compare the displayed price and terms.",
    routeLabel: "Route type",
    allRoutes: "All",
    hotelRoutes: "Hotel links",
    officialRoutes: "Official offers",
    searchRoutes: "Search routes",
    hotelGroup: "Hotel links",
    searchGroup: "Search routes",
    officialGroup: "Official offer pages",
    empty: "No links match this market and route type.",
    selectMarket: "Choose the card issuing country or region first.",
    invalidUrl:
      "Paste a complete Agoda hotel URL, such as https://www.agoda.com/…",
    catalogUnavailable: "The link catalog is unavailable.",
    preservesHotel: "Keeps the hotel URL",
    doesNotPreserveHotel: "Does not keep the hotel URL",
    eligibility: "Check card eligibility and terms",
    openOfficial: "Open official offer",
    openAgoda: "See Agoda price",
    paymentTitle: "Before you book",
    paymentDescription:
      "Eligibility, payment currency, property and booking dates vary by route.",
    markets: {
      GLOBAL: "Global",
      KR: "South Korea",
      JP: "Japan",
      CN: "Mainland China",
      HK: "Hong Kong",
      TW: "Taiwan",
      SG: "Singapore",
      MY: "Malaysia",
      TH: "Thailand",
      VN: "Vietnam",
      ID: "Indonesia",
      PH: "Philippines",
      ANZ: "Australia and New Zealand",
    },
  },
  ko: {
    title: "아고다 호텔 최저가 찾기 | AbsolTools",
    description:
      "아고다 호텔 URL 하나로 카드·제휴 경로별 가격을 비교해 최저가를 찾아보세요.",
    heading: "아고다 호텔 최저가 찾기",
    intro: "아고다 호텔 URL을 붙여넣고 최저가를 찾아보세요.",
    workspaceTitle: "아고다 최저가 찾기",
    workspaceDescription: "호텔 링크 하나로 카드·제휴 경로를 모아 비교합니다.",
    marketLabel: "카드 발급 국가·지역",
    marketPlaceholder: "국가·지역 선택",
    hotelUrlLabel: "아고다 호텔 URL 붙여넣기",
    clear: "지우기",
    urlPlaceholder: "아고다 호텔 URL 붙여넣기 (agoda.com/...)",
    urlNote: "기존 CID와 추적값은 새 링크에 포함하지 않습니다.",
    generate: "최저가 찾기",
    resultsTitle: "아고다 가격 비교",
    resultsDescription:
      "각 경로를 열어 표시 가격과 예약 조건을 직접 비교하세요.",
    routeLabel: "경로 방식",
    allRoutes: "전체",
    hotelRoutes: "호텔 링크",
    officialRoutes: "공식 혜택",
    searchRoutes: "검색 경유",
    hotelGroup: "카드·제휴 경로",
    searchGroup: "검색 경유 링크",
    officialGroup: "공식 혜택 페이지",
    empty: "선택한 국가·지역과 경로 방식에 맞는 링크가 없습니다.",
    selectMarket: "카드 발급 국가·지역을 먼저 선택해 주세요.",
    invalidUrl:
      "https://www.agoda.com/으로 시작하는 아고다 호텔 URL을 붙여 넣어 주세요.",
    catalogUnavailable: "링크 카탈로그를 불러오지 못했습니다.",
    preservesHotel: "입력한 호텔 URL 유지",
    doesNotPreserveHotel: "입력한 호텔 URL 미유지",
    eligibility: "카드 대상과 조건 확인",
    openOfficial: "공식 혜택 보기",
    openAgoda: "가격 확인",
    paymentTitle: "예약 전 확인",
    paymentDescription:
      "카드 대상, 결제 통화, 숙소와 예약 기간은 경로마다 다릅니다.",
    markets: {
      GLOBAL: "글로벌",
      KR: "대한민국",
      JP: "일본",
      CN: "중국 본토",
      HK: "홍콩",
      TW: "대만",
      SG: "싱가포르",
      MY: "말레이시아",
      TH: "태국",
      VN: "베트남",
      ID: "인도네시아",
      PH: "필리핀",
      ANZ: "호주·뉴질랜드",
    },
  },
  es: {
    title: "Encuentra el precio más bajo en Agoda | AbsolTools",
    description:
      "Compara rutas de tarjetas y socios desde una URL de hotel de Agoda para encontrar el precio más bajo.",
    heading: "Encuentra el precio más bajo en Agoda",
    intro:
      "Elige el país emisor de la tarjeta y compara los precios mostrados en Agoda.",
    workspaceTitle: "Comparar precios",
    workspaceDescription:
      "Una URL de hotel, varias rutas de tarjetas y socios.",
    marketLabel: "País o región de emisión de la tarjeta",
    marketPlaceholder: "Elige un país o región",
    hotelUrlLabel: "URL del hotel en Agoda",
    clear: "Borrar",
    urlPlaceholder: "agoda.com/... o https://www.agoda.com/...",
    urlNote: "No se conservan CID ni parámetros de seguimiento.",
    generate: "Comparar precios",
    resultsTitle: "Compara precios en Agoda",
    resultsDescription:
      "Abre cada ruta en Agoda para comparar el precio mostrado y las condiciones.",
    routeLabel: "Tipo de ruta",
    allRoutes: "Todas",
    hotelRoutes: "Enlaces de hotel",
    officialRoutes: "Ofertas oficiales",
    searchRoutes: "Rutas de búsqueda",
    hotelGroup: "Enlaces de hotel",
    searchGroup: "Rutas de búsqueda",
    officialGroup: "Páginas de oferta oficial",
    empty: "No hay enlaces para este mercado y tipo de ruta.",
    selectMarket: "Primero elige el país o región de emisión.",
    invalidUrl:
      "Pega una URL completa de hotel de Agoda, como https://www.agoda.com/…",
    catalogUnavailable: "El catálogo de enlaces no está disponible.",
    preservesHotel: "Conserva la URL del hotel",
    doesNotPreserveHotel: "No conserva la URL del hotel",
    eligibility: "Consulta elegibilidad y condiciones",
    openOfficial: "Abrir oferta oficial",
    openAgoda: "Ver precio en Agoda",
    paymentTitle: "Antes de reservar",
    paymentDescription:
      "La elegibilidad, moneda, alojamiento y fechas cambian según la ruta.",
    markets: {
      GLOBAL: "Global",
      KR: "Corea del Sur",
      JP: "Japón",
      CN: "China continental",
      HK: "Hong Kong",
      TW: "Taiwán",
      SG: "Singapur",
      MY: "Malasia",
      TH: "Tailandia",
      VN: "Vietnam",
      ID: "Indonesia",
      PH: "Filipinas",
      ANZ: "Australia y Nueva Zelanda",
    },
  },
  de: {
    title: "Günstigsten Agoda-Hotelpreis finden | AbsolTools",
    description:
      "Vergleichen Sie Karten- und Partnerrouten über eine Agoda-Hotel-URL, um den günstigsten Preis zu finden.",
    heading: "Günstigsten Agoda-Hotelpreis finden",
    intro:
      "Kartenausgabeland wählen und angezeigte Preise direkt bei Agoda vergleichen.",
    workspaceTitle: "Preise vergleichen",
    workspaceDescription: "Eine Hotel-URL, mehrere Karten- und Partnerrouten.",
    marketLabel: "Ausgabeland oder -region der Karte",
    marketPlaceholder: "Land oder Region wählen",
    hotelUrlLabel: "Agoda-Hotel-URL",
    clear: "Leeren",
    urlPlaceholder: "agoda.com/... oder https://www.agoda.com/...",
    urlNote: "Vorhandene CID- und Tracking-Parameter werden entfernt.",
    generate: "Preise vergleichen",
    resultsTitle: "Agoda-Preise vergleichen",
    resultsDescription:
      "Jede Route bei Agoda öffnen und angezeigte Preise und Bedingungen vergleichen.",
    routeLabel: "Routentyp",
    allRoutes: "Alle",
    hotelRoutes: "Hotellinks",
    officialRoutes: "Offizielle Angebote",
    searchRoutes: "Suchrouten",
    hotelGroup: "Hotellinks",
    searchGroup: "Suchrouten",
    officialGroup: "Offizielle Angebotsseiten",
    empty: "Für diesen Markt und Routentyp gibt es keine Links.",
    selectMarket: "Wählen Sie zuerst das Kartenausgabeland oder die Region.",
    invalidUrl:
      "Fügen Sie eine vollständige Agoda-Hotel-URL ein, z. B. https://www.agoda.com/…",
    catalogUnavailable: "Der Linkkatalog ist nicht verfügbar.",
    preservesHotel: "Hotel-URL bleibt erhalten",
    doesNotPreserveHotel: "Hotel-URL bleibt nicht erhalten",
    eligibility: "Berechtigung und Bedingungen prüfen",
    openOfficial: "Offizielles Angebot öffnen",
    openAgoda: "Agoda-Preis ansehen",
    paymentTitle: "Vor der Buchung",
    paymentDescription:
      "Berechtigung, Währung, Unterkunft und Termine unterscheiden sich je Route.",
    markets: {
      GLOBAL: "Global",
      KR: "Südkorea",
      JP: "Japan",
      CN: "Festlandchina",
      HK: "Hongkong",
      TW: "Taiwan",
      SG: "Singapur",
      MY: "Malaysia",
      TH: "Thailand",
      VN: "Vietnam",
      ID: "Indonesien",
      PH: "Philippinen",
      ANZ: "Australien und Neuseeland",
    },
  },
  ja: {
    title: "アゴダ最安値を探す | AbsolTools",
    description:
      "アゴダのホテルURL一つから、カード・提携経路の表示料金を比べて最安値を探せます。",
    heading: "アゴダ最安値を探す",
    intro: "カード発行国・地域を選び、アゴダで表示料金を比べましょう。",
    workspaceTitle: "最安値を比較",
    workspaceDescription:
      "ホテルURL一つから、カード・提携経路をまとめて比較します。",
    marketLabel: "カード発行国・地域",
    marketPlaceholder: "国・地域を選択",
    hotelUrlLabel: "アゴダのホテルURL",
    clear: "クリア",
    urlPlaceholder: "agoda.com/... または https://www.agoda.com/...",
    urlNote: "既存のCIDと追跡パラメータは引き継ぎません。",
    generate: "最安値を比較",
    resultsTitle: "アゴダ料金を比較",
    resultsDescription:
      "各経路をアゴダで開き、表示料金と適用条件を比較してください。",
    routeLabel: "経路",
    allRoutes: "すべて",
    hotelRoutes: "ホテルリンク",
    officialRoutes: "公式特典",
    searchRoutes: "検索経由",
    hotelGroup: "ホテルリンク",
    searchGroup: "検索経由リンク",
    officialGroup: "公式特典ページ",
    empty: "この国・地域と経路に一致するリンクはありません。",
    selectMarket: "先にカード発行国・地域を選択してください。",
    invalidUrl:
      "https://www.agoda.com/ などの完全なアゴダホテルURLを貼り付けてください。",
    catalogUnavailable: "リンクカタログを読み込めませんでした。",
    preservesHotel: "入力したホテルURLを保持",
    doesNotPreserveHotel: "入力したホテルURLを保持しない",
    eligibility: "対象カードと条件を確認",
    openOfficial: "公式特典を見る",
    openAgoda: "アゴダ料金を見る",
    paymentTitle: "予約前の確認",
    paymentDescription:
      "対象カード、決済通貨、施設、予約期間は経路ごとに異なります。",
    markets: {
      GLOBAL: "グローバル",
      KR: "韓国",
      JP: "日本",
      CN: "中国本土",
      HK: "香港",
      TW: "台湾",
      SG: "シンガポール",
      MY: "マレーシア",
      TH: "タイ",
      VN: "ベトナム",
      ID: "インドネシア",
      PH: "フィリピン",
      ANZ: "オーストラリア・ニュージーランド",
    },
  },
  fr: {
    title: "Trouver le meilleur prix Agoda | AbsolTools",
    description:
      "Comparez les parcours de cartes et partenaires depuis une URL d’hôtel Agoda pour trouver le meilleur prix.",
    heading: "Trouver le meilleur prix Agoda",
    intro:
      "Choisissez le pays émetteur de la carte et comparez les prix affichés dans Agoda.",
    workspaceTitle: "Comparer les prix",
    workspaceDescription:
      "Une URL d’hôtel, plusieurs parcours de cartes et partenaires.",
    marketLabel: "Pays ou région d’émission de la carte",
    marketPlaceholder: "Choisir un pays ou une région",
    hotelUrlLabel: "URL de l’hôtel Agoda",
    clear: "Effacer",
    urlPlaceholder: "agoda.com/... ou https://www.agoda.com/...",
    urlNote: "Les CID et paramètres de suivi existants ne sont pas conservés.",
    generate: "Comparer les prix",
    resultsTitle: "Comparer les prix Agoda",
    resultsDescription:
      "Ouvrez chaque parcours dans Agoda pour comparer le prix affiché et les conditions.",
    routeLabel: "Type de parcours",
    allRoutes: "Tous",
    hotelRoutes: "Liens d’hôtel",
    officialRoutes: "Offres officielles",
    searchRoutes: "Parcours de recherche",
    hotelGroup: "Liens d’hôtel",
    searchGroup: "Parcours de recherche",
    officialGroup: "Pages d’offre officielle",
    empty: "Aucun lien ne correspond à ce marché et à ce parcours.",
    selectMarket: "Choisissez d’abord le pays ou la région d’émission.",
    invalidUrl:
      "Collez une URL complète d’hôtel Agoda, comme https://www.agoda.com/…",
    catalogUnavailable: "Le catalogue de liens est indisponible.",
    preservesHotel: "Conserve l’URL de l’hôtel",
    doesNotPreserveHotel: "Ne conserve pas l’URL de l’hôtel",
    eligibility: "Vérifier l’éligibilité et les conditions",
    openOfficial: "Ouvrir l’offre officielle",
    openAgoda: "Voir le prix Agoda",
    paymentTitle: "Avant de réserver",
    paymentDescription:
      "L’éligibilité, la devise, l’hébergement et les dates diffèrent selon le parcours.",
    markets: {
      GLOBAL: "Mondial",
      KR: "Corée du Sud",
      JP: "Japon",
      CN: "Chine continentale",
      HK: "Hong Kong",
      TW: "Taïwan",
      SG: "Singapour",
      MY: "Malaisie",
      TH: "Thaïlande",
      VN: "Vietnam",
      ID: "Indonésie",
      PH: "Philippines",
      ANZ: "Australie et Nouvelle-Zélande",
    },
  },
  "pt-BR": {
    title: "Encontre o menor preço na Agoda | AbsolTools",
    description:
      "Compare rotas de cartões e parceiros a partir de uma URL de hotel da Agoda para encontrar o menor preço.",
    heading: "Encontre o menor preço na Agoda",
    intro:
      "Escolha o país emissor do cartão e compare os preços mostrados na Agoda.",
    workspaceTitle: "Comparar preços",
    workspaceDescription:
      "Uma URL de hotel, várias rotas de cartões e parceiros.",
    marketLabel: "País ou região emissora do cartão",
    marketPlaceholder: "Escolha um país ou região",
    hotelUrlLabel: "URL do hotel na Agoda",
    clear: "Limpar",
    urlPlaceholder: "agoda.com/... ou https://www.agoda.com/...",
    urlNote: "CID e parâmetros de rastreamento existentes não são mantidos.",
    generate: "Comparar preços",
    resultsTitle: "Compare preços na Agoda",
    resultsDescription:
      "Abra cada rota na Agoda para comparar o preço mostrado e as condições.",
    routeLabel: "Tipo de rota",
    allRoutes: "Todas",
    hotelRoutes: "Links de hotel",
    officialRoutes: "Ofertas oficiais",
    searchRoutes: "Rotas de busca",
    hotelGroup: "Links de hotel",
    searchGroup: "Rotas de busca",
    officialGroup: "Páginas de oferta oficial",
    empty: "Não há links para este mercado e tipo de rota.",
    selectMarket: "Primeiro escolha o país ou região emissora.",
    invalidUrl:
      "Cole uma URL completa de hotel da Agoda, como https://www.agoda.com/…",
    catalogUnavailable: "O catálogo de links não está disponível.",
    preservesHotel: "Mantém a URL do hotel",
    doesNotPreserveHotel: "Não mantém a URL do hotel",
    eligibility: "Confira elegibilidade e condições",
    openOfficial: "Abrir oferta oficial",
    openAgoda: "Ver preço na Agoda",
    paymentTitle: "Antes de reservar",
    paymentDescription:
      "Elegibilidade, moeda, hotel e datas variam conforme a rota.",
    markets: {
      GLOBAL: "Global",
      KR: "Coreia do Sul",
      JP: "Japão",
      CN: "China continental",
      HK: "Hong Kong",
      TW: "Taiwan",
      SG: "Singapura",
      MY: "Malásia",
      TH: "Tailândia",
      VN: "Vietnã",
      ID: "Indonésia",
      PH: "Filipinas",
      ANZ: "Austrália e Nova Zelândia",
    },
  },
  it: {
    title: "Trova il prezzo Agoda più basso | AbsolTools",
    description:
      "Confronta i percorsi di carte e partner da un URL hotel Agoda per trovare il prezzo più basso.",
    heading: "Trova il prezzo Agoda più basso",
    intro:
      "Scegli il paese di emissione della carta e confronta i prezzi mostrati su Agoda.",
    workspaceTitle: "Confronta i prezzi",
    workspaceDescription: "Un URL hotel, più percorsi di carte e partner.",
    marketLabel: "Paese o area di emissione della carta",
    marketPlaceholder: "Scegli paese o area",
    hotelUrlLabel: "URL hotel Agoda",
    clear: "Cancella",
    urlPlaceholder: "agoda.com/... o https://www.agoda.com/...",
    urlNote: "CID e parametri di tracciamento esistenti non vengono mantenuti.",
    generate: "Confronta i prezzi",
    resultsTitle: "Confronta i prezzi Agoda",
    resultsDescription:
      "Apri ogni percorso su Agoda per confrontare prezzo mostrato e condizioni.",
    routeLabel: "Tipo di percorso",
    allRoutes: "Tutti",
    hotelRoutes: "Link hotel",
    officialRoutes: "Offerte ufficiali",
    searchRoutes: "Percorsi di ricerca",
    hotelGroup: "Link hotel",
    searchGroup: "Percorsi di ricerca",
    officialGroup: "Pagine di offerte ufficiali",
    empty: "Nessun link per questo mercato e tipo di percorso.",
    selectMarket: "Prima scegli il paese o l’area di emissione.",
    invalidUrl:
      "Incolla un URL completo di hotel Agoda, ad esempio https://www.agoda.com/…",
    catalogUnavailable: "Il catalogo dei link non è disponibile.",
    preservesHotel: "Mantiene l’URL dell’hotel",
    doesNotPreserveHotel: "Non mantiene l’URL dell’hotel",
    eligibility: "Verifica idoneità e condizioni",
    openOfficial: "Apri offerta ufficiale",
    openAgoda: "Vedi prezzo Agoda",
    paymentTitle: "Prima di prenotare",
    paymentDescription:
      "Idoneità, valuta, struttura e date variano in base al percorso.",
    markets: {
      GLOBAL: "Globale",
      KR: "Corea del Sud",
      JP: "Giappone",
      CN: "Cina continentale",
      HK: "Hong Kong",
      TW: "Taiwan",
      SG: "Singapore",
      MY: "Malesia",
      TH: "Thailandia",
      VN: "Vietnam",
      ID: "Indonesia",
      PH: "Filippine",
      ANZ: "Australia e Nuova Zelanda",
    },
  },
  nl: {
    title: "Vind de laagste Agoda-hotelprijs | AbsolTools",
    description:
      "Vergelijk kaart- en partnerroutes via één Agoda-hotel-URL om de laagste prijs te vinden.",
    heading: "Vind de laagste Agoda-hotelprijs",
    intro:
      "Kies het uitgifteland van de kaart en vergelijk de getoonde prijzen in Agoda.",
    workspaceTitle: "Prijzen vergelijken",
    workspaceDescription: "Eén hotel-URL, meerdere kaart- en partnerroutes.",
    marketLabel: "Uitgifteland of -regio van de kaart",
    marketPlaceholder: "Kies land of regio",
    hotelUrlLabel: "Agoda-hotel-URL",
    clear: "Wissen",
    urlPlaceholder: "agoda.com/... of https://www.agoda.com/...",
    urlNote: "Bestaande CID- en trackingparameters worden niet behouden.",
    generate: "Prijzen vergelijken",
    resultsTitle: "Agoda-prijzen vergelijken",
    resultsDescription:
      "Open elke route in Agoda om de getoonde prijs en voorwaarden te vergelijken.",
    routeLabel: "Routetype",
    allRoutes: "Alle",
    hotelRoutes: "Hotellinks",
    officialRoutes: "Officiële aanbiedingen",
    searchRoutes: "Zoekroutes",
    hotelGroup: "Hotellinks",
    searchGroup: "Zoekroutes",
    officialGroup: "Pagina’s met officiële aanbiedingen",
    empty: "Geen links voor deze markt en dit routetype.",
    selectMarket: "Kies eerst het uitgifteland of de regio van de kaart.",
    invalidUrl:
      "Plak een volledige Agoda-hotel-URL, zoals https://www.agoda.com/…",
    catalogUnavailable: "De linkcatalogus is niet beschikbaar.",
    preservesHotel: "Behoudt de hotel-URL",
    doesNotPreserveHotel: "Behoudt de hotel-URL niet",
    eligibility: "Controleer geschiktheid en voorwaarden",
    openOfficial: "Open officiële aanbieding",
    openAgoda: "Agoda-prijs bekijken",
    paymentTitle: "Voor het boeken",
    paymentDescription:
      "Geschiktheid, valuta, accommodatie en data verschillen per route.",
    markets: {
      GLOBAL: "Wereldwijd",
      KR: "Zuid-Korea",
      JP: "Japan",
      CN: "China",
      HK: "Hongkong",
      TW: "Taiwan",
      SG: "Singapore",
      MY: "Maleisië",
      TH: "Thailand",
      VN: "Vietnam",
      ID: "Indonesië",
      PH: "Filipijnen",
      ANZ: "Australië en Nieuw-Zeeland",
    },
  },
  sv: {
    title: "Hitta lägsta Agoda-hotellpriset | AbsolTools",
    description:
      "Jämför kort- och partnervägar från en Agoda-hotellänk för att hitta det lägsta priset.",
    heading: "Hitta lägsta Agoda-hotellpriset",
    intro: "Välj kortets utfärdandeland och jämför de visade priserna i Agoda.",
    workspaceTitle: "Jämför priser",
    workspaceDescription: "En hotellänk, flera kort- och partnervägar.",
    marketLabel: "Kortets utfärdandeland eller region",
    marketPlaceholder: "Välj land eller region",
    hotelUrlLabel: "Agoda-hotellänk",
    clear: "Rensa",
    urlPlaceholder: "agoda.com/... eller https://www.agoda.com/...",
    urlNote: "Befintliga CID- och spårningsparametrar behålls inte.",
    generate: "Jämför priser",
    resultsTitle: "Jämför Agoda-priser",
    resultsDescription:
      "Öppna varje väg i Agoda för att jämföra visat pris och villkor.",
    routeLabel: "Typ av väg",
    allRoutes: "Alla",
    hotelRoutes: "Hotellänkar",
    officialRoutes: "Officiella erbjudanden",
    searchRoutes: "Sökvägar",
    hotelGroup: "Hotellänkar",
    searchGroup: "Sökvägar",
    officialGroup: "Sidor med officiella erbjudanden",
    empty: "Inga länkar för denna marknad och vägtyp.",
    selectMarket: "Välj först kortets utfärdandeland eller region.",
    invalidUrl:
      "Klistra in en fullständig Agoda-hotellänk, till exempel https://www.agoda.com/…",
    catalogUnavailable: "Länkkatalogen är inte tillgänglig.",
    preservesHotel: "Behåller hotellänken",
    doesNotPreserveHotel: "Behåller inte hotellänken",
    eligibility: "Kontrollera behörighet och villkor",
    openOfficial: "Öppna officiellt erbjudande",
    openAgoda: "Se Agoda-pris",
    paymentTitle: "Innan du bokar",
    paymentDescription:
      "Behörighet, valuta, boende och datum varierar mellan vägar.",
    markets: {
      GLOBAL: "Globalt",
      KR: "Sydkorea",
      JP: "Japan",
      CN: "Fastlandskina",
      HK: "Hongkong",
      TW: "Taiwan",
      SG: "Singapore",
      MY: "Malaysia",
      TH: "Thailand",
      VN: "Vietnam",
      ID: "Indonesien",
      PH: "Filippinerna",
      ANZ: "Australien och Nya Zeeland",
    },
  },
  cs: {
    title: "Najděte nejnižší cenu hotelu na Agoda | AbsolTools",
    description:
      "Porovnejte cesty karet a partnerů z jedné adresy hotelu Agoda a najděte nejnižší cenu.",
    heading: "Najděte nejnižší cenu hotelu na Agoda",
    intro: "Zvolte zemi vydání karty a porovnejte zobrazené ceny v Agoda.",
    workspaceTitle: "Porovnat ceny",
    workspaceDescription: "Jedna adresa hotelu, více cest karet a partnerů.",
    marketLabel: "Země nebo oblast vydání karty",
    marketPlaceholder: "Vyberte zemi nebo oblast",
    hotelUrlLabel: "Odkaz na hotel Agoda",
    clear: "Vymazat",
    urlPlaceholder: "agoda.com/... nebo https://www.agoda.com/...",
    urlNote: "Stávající CID a sledovací parametry se nezachovají.",
    generate: "Porovnat ceny",
    resultsTitle: "Porovnat ceny na Agoda",
    resultsDescription:
      "Otevřete každou cestu v Agoda a porovnejte zobrazenou cenu a podmínky.",
    routeLabel: "Typ cesty",
    allRoutes: "Vše",
    hotelRoutes: "Odkazy na hotely",
    officialRoutes: "Oficiální nabídky",
    searchRoutes: "Vyhledávací cesty",
    hotelGroup: "Odkazy na hotely",
    searchGroup: "Vyhledávací cesty",
    officialGroup: "Stránky oficiálních nabídek",
    empty: "Pro tento trh a typ cesty nejsou žádné odkazy.",
    selectMarket: "Nejprve vyberte zemi nebo oblast vydání karty.",
    invalidUrl:
      "Vložte úplný odkaz na hotel Agoda, například https://www.agoda.com/…",
    catalogUnavailable: "Katalog odkazů není k dispozici.",
    preservesHotel: "Zachová odkaz na hotel",
    doesNotPreserveHotel: "Nezachová odkaz na hotel",
    eligibility: "Ověřte způsobilost a podmínky",
    openOfficial: "Otevřít oficiální nabídku",
    openAgoda: "Zobrazit cenu na Agoda",
    paymentTitle: "Před rezervací",
    paymentDescription:
      "Způsobilost, měna, ubytování i termíny se liší podle cesty.",
    markets: {
      GLOBAL: "Globální",
      KR: "Jižní Korea",
      JP: "Japonsko",
      CN: "Pevninská Čína",
      HK: "Hongkong",
      TW: "Tchaj-wan",
      SG: "Singapur",
      MY: "Malajsie",
      TH: "Thajsko",
      VN: "Vietnam",
      ID: "Indonésie",
      PH: "Filipíny",
      ANZ: "Austrálie a Nový Zéland",
    },
  },
  pl: {
    title: "Znajdź najniższą cenę hotelu Agoda | AbsolTools",
    description:
      "Porównaj ścieżki kart i partnerów z jednego linku hotelowego Agoda, aby znaleźć najniższą cenę.",
    heading: "Znajdź najniższą cenę hotelu Agoda",
    intro: "Wybierz kraj wydania karty i porównaj ceny wyświetlane w Agoda.",
    workspaceTitle: "Porównaj ceny",
    workspaceDescription:
      "Jeden link hotelowy, wiele ścieżek kart i partnerów.",
    marketLabel: "Kraj lub region wydania karty",
    marketPlaceholder: "Wybierz kraj lub region",
    hotelUrlLabel: "Link do hotelu Agoda",
    clear: "Wyczyść",
    urlPlaceholder: "agoda.com/... lub https://www.agoda.com/...",
    urlNote: "Istniejące parametry CID i śledzenia nie są zachowywane.",
    generate: "Porównaj ceny",
    resultsTitle: "Porównaj ceny na Agoda",
    resultsDescription:
      "Otwórz każdą ścieżkę w Agoda, aby porównać wyświetlaną cenę i warunki.",
    routeLabel: "Typ ścieżki",
    allRoutes: "Wszystkie",
    hotelRoutes: "Linki do hoteli",
    officialRoutes: "Oferty oficjalne",
    searchRoutes: "Ścieżki wyszukiwania",
    hotelGroup: "Linki do hoteli",
    searchGroup: "Ścieżki wyszukiwania",
    officialGroup: "Strony ofert oficjalnych",
    empty: "Brak linków dla tego rynku i typu ścieżki.",
    selectMarket: "Najpierw wybierz kraj lub region wydania karty.",
    invalidUrl: "Wklej pełny link do hotelu Agoda, np. https://www.agoda.com/…",
    catalogUnavailable: "Katalog linków jest niedostępny.",
    preservesHotel: "Zachowuje link do hotelu",
    doesNotPreserveHotel: "Nie zachowuje linku do hotelu",
    eligibility: "Sprawdź uprawnienia i warunki",
    openOfficial: "Otwórz ofertę oficjalną",
    openAgoda: "Zobacz cenę na Agoda",
    paymentTitle: "Przed rezerwacją",
    paymentDescription:
      "Uprawnienia, waluta, obiekt i terminy różnią się zależnie od ścieżki.",
    markets: {
      GLOBAL: "Globalnie",
      KR: "Korea Południowa",
      JP: "Japonia",
      CN: "Chiny kontynentalne",
      HK: "Hongkong",
      TW: "Tajwan",
      SG: "Singapur",
      MY: "Malezja",
      TH: "Tajlandia",
      VN: "Wietnam",
      ID: "Indonezja",
      PH: "Filipiny",
      ANZ: "Australia i Nowa Zelandia",
    },
  },
  da: {
    title: "Find den laveste Agoda-hotelpris | AbsolTools",
    description:
      "Sammenlign kort- og partnerruter fra én Agoda-hotellink for at finde den laveste pris.",
    heading: "Find den laveste Agoda-hotelpris",
    intro: "Vælg kortets udstedelsesland og sammenlign viste priser i Agoda.",
    workspaceTitle: "Sammenlign priser",
    workspaceDescription: "Én hotellink, flere kort- og partnerruter.",
    marketLabel: "Kortets udstedelsesland eller region",
    marketPlaceholder: "Vælg land eller region",
    hotelUrlLabel: "Agoda-hotellink",
    clear: "Ryd",
    urlPlaceholder: "agoda.com/... eller https://www.agoda.com/...",
    urlNote: "Eksisterende CID- og sporingsparametre bevares ikke.",
    generate: "Sammenlign priser",
    resultsTitle: "Sammenlign Agoda-priser",
    resultsDescription:
      "Åbn hver rute i Agoda for at sammenligne vist pris og vilkår.",
    routeLabel: "Rutetype",
    allRoutes: "Alle",
    hotelRoutes: "Hotellinks",
    officialRoutes: "Officielle tilbud",
    searchRoutes: "Søgeruter",
    hotelGroup: "Hotellinks",
    searchGroup: "Søgeruter",
    officialGroup: "Sider med officielle tilbud",
    empty: "Ingen links for dette marked og denne rutetype.",
    selectMarket: "Vælg først kortets udstedelsesland eller region.",
    invalidUrl: "Indsæt en fuld Agoda-hotellink, fx https://www.agoda.com/…",
    catalogUnavailable: "Linkkataloget er ikke tilgængeligt.",
    preservesHotel: "Bevarer hotellinket",
    doesNotPreserveHotel: "Bevarer ikke hotellinket",
    eligibility: "Kontrollér berettigelse og vilkår",
    openOfficial: "Åbn officielt tilbud",
    openAgoda: "Se Agoda-pris",
    paymentTitle: "Før du bestiller",
    paymentDescription:
      "Berettigelse, valuta, overnatningssted og datoer varierer efter rute.",
    markets: {
      GLOBAL: "Global",
      KR: "Sydkorea",
      JP: "Japan",
      CN: "Kina",
      HK: "Hongkong",
      TW: "Taiwan",
      SG: "Singapore",
      MY: "Malaysia",
      TH: "Thailand",
      VN: "Vietnam",
      ID: "Indonesien",
      PH: "Filippinerne",
      ANZ: "Australien og New Zealand",
    },
  },
  no: {
    title: "Finn den laveste Agoda-hotellprisen | AbsolTools",
    description:
      "Sammenlign kort- og partnerruter fra én Agoda-hotellenke for å finne den laveste prisen.",
    heading: "Finn den laveste Agoda-hotellprisen",
    intro: "Velg kortets utstedelsesland og sammenlign viste priser i Agoda.",
    workspaceTitle: "Sammenlign priser",
    workspaceDescription: "Én hotellenke, flere kort- og partnerruter.",
    marketLabel: "Kortets utstedelsesland eller region",
    marketPlaceholder: "Velg land eller region",
    hotelUrlLabel: "Agoda-hotellenke",
    clear: "Tøm",
    urlPlaceholder: "agoda.com/... eller https://www.agoda.com/...",
    urlNote: "Eksisterende CID- og sporingsparametere beholdes ikke.",
    generate: "Sammenlign priser",
    resultsTitle: "Sammenlign Agoda-priser",
    resultsDescription:
      "Åpne hver rute i Agoda for å sammenligne vist pris og vilkår.",
    routeLabel: "Rutetype",
    allRoutes: "Alle",
    hotelRoutes: "Hotellenker",
    officialRoutes: "Offisielle tilbud",
    searchRoutes: "Søkeruter",
    hotelGroup: "Hotellenker",
    searchGroup: "Søkeruter",
    officialGroup: "Sider med offisielle tilbud",
    empty: "Ingen lenker for dette markedet og denne rutetypen.",
    selectMarket: "Velg først kortets utstedelsesland eller region.",
    invalidUrl:
      "Lim inn en fullstendig Agoda-hotellenke, for eksempel https://www.agoda.com/…",
    catalogUnavailable: "Lenkekatalogen er ikke tilgjengelig.",
    preservesHotel: "Beholder hotelllenken",
    doesNotPreserveHotel: "Beholder ikke hotelllenken",
    eligibility: "Kontroller kvalifisering og vilkår",
    openOfficial: "Åpne offisielt tilbud",
    openAgoda: "Se Agoda-pris",
    paymentTitle: "Før du bestiller",
    paymentDescription:
      "Kvalifisering, valuta, overnatting og datoer varierer etter rute.",
    markets: {
      GLOBAL: "Globalt",
      KR: "Sør-Korea",
      JP: "Japan",
      CN: "Fastlands-Kina",
      HK: "Hongkong",
      TW: "Taiwan",
      SG: "Singapore",
      MY: "Malaysia",
      TH: "Thailand",
      VN: "Vietnam",
      ID: "Indonesia",
      PH: "Filippinene",
      ANZ: "Australia og New Zealand",
    },
  },
  ar: {
    title: "اعثر على أقل سعر لفندق أجودا | AbsolTools",
    description:
      "قارن مسارات البطاقات والشركاء من رابط فندق أجودا واحد للعثور على أقل سعر.",
    heading: "اعثر على أقل سعر لفندق أجودا",
    intro: "اختر بلد إصدار البطاقة وقارن الأسعار المعروضة في أجودا.",
    workspaceTitle: "مقارنة الأسعار",
    workspaceDescription: "رابط فندق واحد، ومسارات متعددة للبطاقات والشركاء.",
    marketLabel: "بلد أو منطقة إصدار البطاقة",
    marketPlaceholder: "اختر بلداً أو منطقة",
    hotelUrlLabel: "رابط فندق أجودا",
    clear: "مسح",
    urlPlaceholder: "agoda.com/... أو https://www.agoda.com/...",
    urlNote: "لا يتم الاحتفاظ بمعرّف CID أو معلمات التتبع الحالية.",
    generate: "مقارنة الأسعار",
    resultsTitle: "قارن أسعار أجودا",
    resultsDescription: "افتح كل مسار في أجودا لمقارنة السعر المعروض والشروط.",
    routeLabel: "نوع المسار",
    allRoutes: "الكل",
    hotelRoutes: "روابط الفندق",
    officialRoutes: "عروض رسمية",
    searchRoutes: "مسارات بحث",
    hotelGroup: "روابط الفندق",
    searchGroup: "مسارات بحث",
    officialGroup: "صفحات العروض الرسمية",
    empty: "لا توجد روابط لهذا السوق ونوع المسار.",
    selectMarket: "اختر بلد أو منطقة إصدار البطاقة أولاً.",
    invalidUrl:
      "الصق رابطاً كاملاً لفندق في أجودا، مثل https://www.agoda.com/…",
    catalogUnavailable: "كتالوج الروابط غير متاح.",
    preservesHotel: "يحتفظ برابط الفندق",
    doesNotPreserveHotel: "لا يحتفظ برابط الفندق",
    eligibility: "تحقق من الأهلية والشروط",
    openOfficial: "فتح العرض الرسمي",
    openAgoda: "عرض سعر أجودا",
    paymentTitle: "قبل الحجز",
    paymentDescription:
      "تختلف الأهلية والعملة ومكان الإقامة والتواريخ حسب المسار.",
    markets: {
      GLOBAL: "عالمي",
      KR: "كوريا الجنوبية",
      JP: "اليابان",
      CN: "الصين القارية",
      HK: "هونغ كونغ",
      TW: "تايوان",
      SG: "سنغافورة",
      MY: "ماليزيا",
      TH: "تايلاند",
      VN: "فيتنام",
      ID: "إندونيسيا",
      PH: "الفلبين",
      ANZ: "أستراليا ونيوزيلندا",
    },
  },
  "zh-TW": {
    title: "尋找 Agoda 飯店最低價 | AbsolTools",
    description: "從一個 Agoda 飯店網址比較信用卡與合作夥伴路徑，尋找最低價。",
    heading: "尋找 Agoda 飯店最低價",
    intro: "先選擇發卡國家或地區，再比較 Agoda 顯示的價格。",
    workspaceTitle: "比較價格",
    workspaceDescription: "一個飯店網址，多個信用卡與合作夥伴路徑。",
    marketLabel: "發卡國家／地區",
    marketPlaceholder: "選擇國家／地區",
    hotelUrlLabel: "Agoda 飯店網址",
    clear: "清除",
    urlPlaceholder: "agoda.com/... 或 https://www.agoda.com/...",
    urlNote: "不保留原有 CID 和追蹤參數。",
    generate: "比較價格",
    resultsTitle: "比較 Agoda 價格",
    resultsDescription: "在 Agoda 開啟各路徑，比較顯示價格與適用條件。",
    routeLabel: "路徑類型",
    allRoutes: "全部",
    hotelRoutes: "飯店連結",
    officialRoutes: "官方優惠",
    searchRoutes: "搜尋路徑",
    hotelGroup: "飯店連結",
    searchGroup: "搜尋路徑",
    officialGroup: "官方優惠頁面",
    empty: "沒有符合此市場和路徑類型的連結。",
    selectMarket: "請先選擇發卡國家／地區。",
    invalidUrl: "請貼上完整 Agoda 飯店網址，例如 https://www.agoda.com/…",
    catalogUnavailable: "無法取得連結目錄。",
    preservesHotel: "保留輸入的飯店網址",
    doesNotPreserveHotel: "不保留輸入的飯店網址",
    eligibility: "確認卡別資格與條件",
    openOfficial: "查看官方優惠",
    openAgoda: "查看 Agoda 價格",
    paymentTitle: "預訂前確認",
    paymentDescription: "資格、付款幣別、住宿和預訂日期會因路徑而異。",
    markets: {
      GLOBAL: "全球",
      KR: "韓國",
      JP: "日本",
      CN: "中國大陸",
      HK: "香港",
      TW: "台灣",
      SG: "新加坡",
      MY: "馬來西亞",
      TH: "泰國",
      VN: "越南",
      ID: "印尼",
      PH: "菲律賓",
      ANZ: "澳洲及紐西蘭",
    },
  },
  tr: {
    title: "En düşük Agoda otel fiyatını bulun | AbsolTools",
    description:
      "En düşük fiyatı bulmak için tek bir Agoda otel bağlantısından kart ve iş ortağı yollarını karşılaştırın.",
    heading: "En düşük Agoda otel fiyatını bulun",
    intro:
      "Kartın düzenlendiği ülkeyi seçin ve Agoda’da gösterilen fiyatları karşılaştırın.",
    workspaceTitle: "Fiyatları karşılaştır",
    workspaceDescription:
      "Tek otel bağlantısı, birden çok kart ve iş ortağı yolu.",
    marketLabel: "Kartın düzenlendiği ülke veya bölge",
    marketPlaceholder: "Ülke veya bölge seçin",
    hotelUrlLabel: "Agoda otel bağlantısı",
    clear: "Temizle",
    urlPlaceholder: "agoda.com/... veya https://www.agoda.com/...",
    urlNote: "Mevcut CID ve izleme parametreleri korunmaz.",
    generate: "Fiyatları karşılaştır",
    resultsTitle: "Agoda fiyatlarını karşılaştır",
    resultsDescription:
      "Gösterilen fiyatı ve koşulları karşılaştırmak için her yolu Agoda’da açın.",
    routeLabel: "Yol türü",
    allRoutes: "Tümü",
    hotelRoutes: "Otel bağlantıları",
    officialRoutes: "Resmî fırsatlar",
    searchRoutes: "Arama yolları",
    hotelGroup: "Otel bağlantıları",
    searchGroup: "Arama yolları",
    officialGroup: "Resmî fırsat sayfaları",
    empty: "Bu pazar ve yol türü için bağlantı yok.",
    selectMarket: "Önce kartın düzenlendiği ülkeyi veya bölgeyi seçin.",
    invalidUrl:
      "https://www.agoda.com/… gibi tam bir Agoda otel bağlantısı yapıştırın.",
    catalogUnavailable: "Bağlantı kataloğu kullanılamıyor.",
    preservesHotel: "Otel bağlantısını korur",
    doesNotPreserveHotel: "Otel bağlantısını korumaz",
    eligibility: "Uygunluğu ve koşulları kontrol edin",
    openOfficial: "Resmî fırsatı aç",
    openAgoda: "Agoda fiyatını gör",
    paymentTitle: "Rezervasyondan önce",
    paymentDescription:
      "Uygunluk, para birimi, tesis ve tarihler yola göre değişir.",
    markets: {
      GLOBAL: "Küresel",
      KR: "Güney Kore",
      JP: "Japonya",
      CN: "Çin ana karası",
      HK: "Hong Kong",
      TW: "Tayvan",
      SG: "Singapur",
      MY: "Malezya",
      TH: "Tayland",
      VN: "Vietnam",
      ID: "Endonezya",
      PH: "Filipinler",
      ANZ: "Avustralya ve Yeni Zelanda",
    },
  },
};
