import { units } from "@plaintool/unit-converter-core";
import type { UnitConverterLocale } from "./i18n";

const specialUnitIds = [
  "nautical-mile",
  "milligram",
  "metric-ton",
  "celsius",
  "fahrenheit",
  "kelvin",
  "square-centimeter",
  "square-meter",
  "square-kilometer",
  "square-foot",
  "square-yard",
  "cubic-meter",
  "us-fluid-ounce",
  "us-cup",
  "us-pint",
  "us-quart",
  "us-gallon",
  "uk-pint",
  "uk-gallon",
  "knot",
] as const;

type SpecialUnitId = (typeof specialUnitIds)[number];

function specialNames(
  ...names: readonly [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ]
): Record<SpecialUnitId, string> {
  return Object.fromEntries(
    specialUnitIds.map((id, index) => [id, names[index]]),
  ) as Record<SpecialUnitId, string>;
}

const specialUnitNames: Record<
  UnitConverterLocale,
  Record<SpecialUnitId, string>
> = {
  en: specialNames(
    "nautical mile",
    "milligram",
    "metric tonne",
    "degree Celsius",
    "degree Fahrenheit",
    "kelvin",
    "square centimeter",
    "square meter",
    "square kilometer",
    "square foot",
    "square yard",
    "cubic meter",
    "US fluid ounce",
    "US cup",
    "US pint",
    "US quart",
    "US gallon",
    "UK pint",
    "UK gallon",
    "knot",
  ),
  ko: specialNames(
    "해리",
    "밀리그램",
    "미터톤",
    "섭씨",
    "화씨",
    "켈빈",
    "제곱센티미터",
    "제곱미터",
    "제곱킬로미터",
    "제곱피트",
    "제곱야드",
    "세제곱미터",
    "미국 액량 온스",
    "미국 컵",
    "미국 파인트",
    "미국 쿼트",
    "미국 갤런",
    "영국 파인트",
    "영국 갤런",
    "노트",
  ),
  es: specialNames(
    "milla náutica",
    "miligramo",
    "tonelada métrica",
    "grado Celsius",
    "grado Fahrenheit",
    "kelvin",
    "centímetro cuadrado",
    "metro cuadrado",
    "kilómetro cuadrado",
    "pie cuadrado",
    "yarda cuadrada",
    "metro cúbico",
    "onza líquida estadounidense",
    "taza estadounidense",
    "pinta estadounidense",
    "cuarto estadounidense",
    "galón estadounidense",
    "pinta imperial",
    "galón imperial",
    "nudo",
  ),
  de: specialNames(
    "Seemeile",
    "Milligramm",
    "metrische Tonne",
    "Grad Celsius",
    "Grad Fahrenheit",
    "Kelvin",
    "Quadratzentimeter",
    "Quadratmeter",
    "Quadratkilometer",
    "Quadratfuß",
    "Quadratyard",
    "Kubikmeter",
    "US-Flüssigunze",
    "US-Cup",
    "US-Pint",
    "US-Quart",
    "US-Gallone",
    "britisches Pint",
    "britische Gallone",
    "Knoten",
  ),
  ja: specialNames(
    "海里",
    "ミリグラム",
    "メートルトン",
    "摂氏",
    "華氏",
    "ケルビン",
    "平方センチメートル",
    "平方メートル",
    "平方キロメートル",
    "平方フィート",
    "平方ヤード",
    "立方メートル",
    "米液量オンス",
    "米カップ",
    "米パイント",
    "米クォート",
    "米ガロン",
    "英パイント",
    "英ガロン",
    "ノット",
  ),
  fr: specialNames(
    "mille marin",
    "milligramme",
    "tonne métrique",
    "degré Celsius",
    "degré Fahrenheit",
    "kelvin",
    "centimètre carré",
    "mètre carré",
    "kilomètre carré",
    "pied carré",
    "yard carré",
    "mètre cube",
    "once liquide américaine",
    "tasse américaine",
    "pinte américaine",
    "quart américain",
    "gallon américain",
    "pinte impériale",
    "gallon impérial",
    "nœud",
  ),
  "pt-BR": specialNames(
    "milha náutica",
    "miligrama",
    "tonelada métrica",
    "grau Celsius",
    "grau Fahrenheit",
    "kelvin",
    "centímetro quadrado",
    "metro quadrado",
    "quilômetro quadrado",
    "pé quadrado",
    "jarda quadrada",
    "metro cúbico",
    "onça líquida americana",
    "xícara americana",
    "pinta americana",
    "quarto americano",
    "galão americano",
    "pinta imperial",
    "galão imperial",
    "nó",
  ),
  it: specialNames(
    "miglio nautico",
    "milligrammo",
    "tonnellata metrica",
    "grado Celsius",
    "grado Fahrenheit",
    "kelvin",
    "centimetro quadrato",
    "metro quadrato",
    "chilometro quadrato",
    "piede quadrato",
    "iarda quadrata",
    "metro cubo",
    "oncia liquida statunitense",
    "tazza statunitense",
    "pinta statunitense",
    "quarto statunitense",
    "gallone statunitense",
    "pinta imperiale",
    "gallone imperiale",
    "nodo",
  ),
  nl: specialNames(
    "zeemijl",
    "milligram",
    "metrische ton",
    "graad Celsius",
    "graad Fahrenheit",
    "kelvin",
    "vierkante centimeter",
    "vierkante meter",
    "vierkante kilometer",
    "vierkante voet",
    "vierkante yard",
    "kubieke meter",
    "Amerikaanse vloeistofons",
    "Amerikaanse cup",
    "Amerikaanse pint",
    "Amerikaanse quart",
    "Amerikaanse gallon",
    "Britse pint",
    "Britse gallon",
    "knoop",
  ),
  sv: specialNames(
    "sjömil",
    "milligram",
    "metriskt ton",
    "grad Celsius",
    "grad Fahrenheit",
    "kelvin",
    "kvadratcentimeter",
    "kvadratmeter",
    "kvadratkilometer",
    "kvadratfot",
    "kvadratyard",
    "kubikmeter",
    "amerikanskt vätskeuns",
    "amerikansk cup",
    "amerikansk pint",
    "amerikansk quart",
    "amerikansk gallon",
    "brittisk pint",
    "brittisk gallon",
    "knop",
  ),
  cs: specialNames(
    "námořní míle",
    "miligram",
    "metrická tuna",
    "stupeň Celsia",
    "stupeň Fahrenheita",
    "kelvin",
    "centimetr čtvereční",
    "metr čtvereční",
    "kilometr čtvereční",
    "čtvereční stopa",
    "čtvereční yard",
    "metr krychlový",
    "americká tekutá unce",
    "americký šálek",
    "americká pinta",
    "americký kvart",
    "americký galon",
    "britská pinta",
    "britský galon",
    "uzel",
  ),
  pl: specialNames(
    "mila morska",
    "miligram",
    "tona metryczna",
    "stopień Celsjusza",
    "stopień Fahrenheita",
    "kelwin",
    "centymetr kwadratowy",
    "metr kwadratowy",
    "kilometr kwadratowy",
    "stopa kwadratowa",
    "jard kwadratowy",
    "metr sześcienny",
    "amerykańska uncja płynu",
    "kubek amerykański",
    "pinta amerykańska",
    "kwarta amerykańska",
    "galon amerykański",
    "pinta brytyjska",
    "galon brytyjski",
    "węzeł",
  ),
  da: specialNames(
    "sømil",
    "milligram",
    "metrisk ton",
    "grad celsius",
    "grad fahrenheit",
    "kelvin",
    "kvadratcentimeter",
    "kvadratmeter",
    "kvadratkilometer",
    "kvadratfod",
    "kvadratyard",
    "kubikmeter",
    "amerikansk fluid ounce",
    "amerikansk cup",
    "amerikansk pint",
    "amerikansk quart",
    "amerikansk gallon",
    "britisk pint",
    "britisk gallon",
    "knob",
  ),
  no: specialNames(
    "nautisk mil",
    "milligram",
    "metrisk tonn",
    "grad Celsius",
    "grad Fahrenheit",
    "kelvin",
    "kvadratcentimeter",
    "kvadratmeter",
    "kvadratkilometer",
    "kvadratfot",
    "kvadratyard",
    "kubikkmeter",
    "amerikansk fluid ounce",
    "amerikansk cup",
    "amerikansk pint",
    "amerikansk quart",
    "amerikansk gallon",
    "britisk pint",
    "britisk gallon",
    "knop",
  ),
  ar: specialNames(
    "ميل بحري",
    "مليغرام",
    "طن متري",
    "درجة مئوية",
    "درجة فهرنهايت",
    "كلفن",
    "سنتيمتر مربع",
    "متر مربع",
    "كيلومتر مربع",
    "قدم مربع",
    "ياردة مربعة",
    "متر مكعب",
    "أونصة سائلة أمريكية",
    "كوب أمريكي",
    "باينت أمريكي",
    "كوارت أمريكي",
    "غالون أمريكي",
    "باينت بريطاني",
    "غالون بريطاني",
    "عقدة",
  ),
  "zh-TW": specialNames(
    "海里",
    "毫克",
    "公噸",
    "攝氏度",
    "華氏度",
    "克耳文",
    "平方公分",
    "平方公尺",
    "平方公里",
    "平方英尺",
    "平方碼",
    "立方公尺",
    "美制液量盎司",
    "美制杯",
    "美制品脫",
    "美制夸脫",
    "美制加侖",
    "英制品脫",
    "英制加侖",
    "節",
  ),
  tr: specialNames(
    "deniz mili",
    "miligram",
    "metrik ton",
    "santigrat derece",
    "Fahrenhayt derece",
    "kelvin",
    "santimetrekare",
    "metrekare",
    "kilometrekare",
    "fit kare",
    "yarda kare",
    "metreküp",
    "ABD sıvı onsu",
    "ABD kupası",
    "ABD pinti",
    "ABD kuartı",
    "ABD galonu",
    "İngiliz pinti",
    "İngiliz galonu",
    "knot",
  ),
};

const intlUnitIds = new Set(
  units
    .map((unit) => unit.id)
    .filter((id) => !specialUnitIds.includes(id as SpecialUnitId)),
);

function intlUnitName(locale: UnitConverterLocale, unit: string): string {
  return new Intl.NumberFormat(locale, {
    style: "unit",
    unit,
    unitDisplay: "long",
  })
    .formatToParts(1)
    .filter((part) => part.type === "unit")
    .map((part) => part.value)
    .join(" ");
}

export function unitNamesFor(
  locale: UnitConverterLocale,
): Record<string, string> {
  return Object.fromEntries(
    units.map((unit) => {
      const special = specialUnitNames[locale][unit.id as SpecialUnitId];
      const label =
        special ??
        (intlUnitIds.has(unit.id) ? intlUnitName(locale, unit.id) : "");
      if (!label)
        throw new Error(`Missing ${locale} unit label for ${unit.id}.`);
      return [unit.id, label];
    }),
  );
}
